### ISSUE TITLE
remove: source installer as it is replaced by cloudmesh-installer

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-cloud#154]
source install
source update

release 

```
cloudmesh:
  source:
    location: ~/Desktop/github/cloudmesh
    packages:
      cloudmesh-common: https://github.com/cloudmesh/cloudmesh-common
      cloudmesh-cmd5: https://github.com/cloudmesh/cloudmesh-cmd5
      cloudmesh-openapi: https://github.com/cloudmesh/cloudmesh-openapi
      cloudmesh-sys: https://github.com/cloudmesh/cloudmesh-sys
      cloudmesh-cm4: https://github.com/cloudmesh/cloudmesh-cm4
```
